// Master department/program catalog, split by college stream. Which list a
// college sees is inferred from its name (no explicit college-type field
// exists on the institution record) — a college name containing an
// engineering keyword gets ENGINEERING_DEPARTMENTS, one containing an arts/
// science/commerce keyword gets ARTS_SCIENCE_DEPARTMENTS, and anything
// ambiguous gets the union of both so nothing is hidden by a bad guess.

export const ENGINEERING_DEPARTMENTS = [
  "B.E. Computer Science and Engineering (CSE)",
  "B.E. Electronics and Communication Engineering (ECE)",
  "B.E. Electrical and Electronics Engineering (EEE)",
  "B.E. Electrical Engineering (EE)",
  "B.E. Mechanical Engineering",
  "B.E. Civil Engineering",
  "B.E. Automobile Engineering",
  "B.E. Mechatronics Engineering",
  "B.E. Robotics and Automation",
  "B.E. Biomedical Engineering",
  "B.E. Aeronautical Engineering",
  "B.E. Aerospace Engineering",
  "B.E. Marine Engineering",
  "B.E. Mining Engineering",
  "B.E. Industrial Engineering",
  "B.E. Production Engineering",
  "B.E. Manufacturing Engineering",
  "B.E. Printing Technology",
  "B.E. Electronics and Instrumentation Engineering (EIE)",
  "B.E. Instrumentation and Control Engineering",
  "B.E. Environmental Engineering",
  "B.E. Geoinformatics",
  "B.E. Petrochemical Engineering",
  "B.E. Metallurgical Engineering",
  "B.E. Ceramic Engineering",
  "B.E. Agricultural Engineering",
  "B.E. Computer Science and Design",
  "B.Tech. Information Technology (IT)",
  "B.Tech. Artificial Intelligence and Data Science (AI & DS)",
  "B.Tech. Artificial Intelligence and Machine Learning (AI & ML)",
  "B.Tech. Data Science",
  "B.Tech. Biotechnology",
  "B.Tech. Chemical Engineering",
  "B.Tech. Food Technology",
  "B.Tech. Pharmaceutical Technology",
  "B.Tech. Textile Technology",
  "B.Tech. Textile Chemistry",
  "B.Tech. Fashion Technology",
  "B.Tech. Leather Technology",
  "B.Tech. Polymer Technology",
  "B.Tech. Plastic Technology",
  "B.Tech. Industrial Biotechnology",
  "B.Tech. Information Science and Engineering (ISE)",
  "B.Tech. Computer Science and Business Systems (CSBS)",
  "B.Tech. Computer Science and Engineering (Cyber Security)",
  "B.Tech. Computer Science and Engineering (Artificial Intelligence)",
  "B.Tech. Computer Science and Engineering (Data Science)",
  "B.Tech. Computer Science and Engineering (Internet of Things)",
  "B.Tech. Computer Science and Engineering (Blockchain Technology)",
  "B.Tech. Computer Science and Engineering (Cloud Computing)",
  "B.Tech. Computer Science and Engineering (AI & Cyber Security)",
  "B.Tech. Computer Science and Engineering (IoT and Cyber Security including Blockchain)",
  "B.Tech. Electronics Engineering (VLSI Design and Technology)",
  "B.Tech. Electronics and Computer Engineering",
  "B.Tech. Electronics Engineering",
  "B.Tech. Renewable Energy Engineering",
  "B.Tech. Energy Engineering",
  "B.Tech. Nanotechnology",
  "B.Tech. Medical Electronics",
] as const;

export const ARTS_SCIENCE_DEPARTMENTS = [
  "B.A. English",
  "B.A. Tamil",
  "B.A. History",
  "B.A. Economics",
  "B.A. Sociology",
  "B.A. Political Science",
  "B.A. Public Administration",
  "B.A. Journalism",
  "B.A. Visual Communication",
  "B.A. Philosophy",
  "B.A. Geography",
  "B.A. Anthropology",
  "B.A. Criminology",
  "B.A. Defence and Strategic Studies",
  "B.A. Tourism and Travel Management",
  "B.A. Functional English",
  "B.A. Linguistics",
  "B.A. Archaeology",
  "B.A. Rural Development",
  "B.Sc. Computer Science",
  "B.Sc. Information Technology",
  "B.Sc. Computer Technology",
  "B.Sc. Software Systems",
  "B.Sc. Information Systems",
  "B.Sc. Artificial Intelligence",
  "B.Sc. Artificial Intelligence and Machine Learning",
  "B.Sc. Data Science",
  "B.Sc. Cyber Security",
  "B.Sc. Mathematics",
  "B.Sc. Statistics",
  "B.Sc. Physics",
  "B.Sc. Chemistry",
  "B.Sc. Electronics",
  "B.Sc. Electronics and Communication",
  "B.Sc. Biotechnology",
  "B.Sc. Biochemistry",
  "B.Sc. Microbiology",
  "B.Sc. Botany",
  "B.Sc. Zoology",
  "B.Sc. Psychology",
  "B.Sc. Forensic Science",
  "B.Sc. Environmental Science",
  "B.Sc. Geography",
  "B.Sc. Geology",
  "B.Sc. Marine Biology",
  "B.Sc. Fisheries Science",
  "B.Sc. Agriculture",
  "B.Sc. Horticulture",
  "B.Sc. Forestry",
  "B.Sc. Home Science",
  "B.Sc. Nutrition and Dietetics",
  "B.Sc. Food Science and Nutrition",
  "B.Sc. Costume Design and Fashion",
  "B.Sc. Fashion Technology",
  "B.Sc. Visual Communication",
  "B.Sc. Animation and Multimedia",
  "B.Sc. Hotel Management and Catering Science",
  "B.Sc. Medical Laboratory Technology",
  "B.Sc. Clinical Laboratory Technology",
  "B.Sc. Radiology and Imaging Technology",
  "B.Sc. Operation Theatre Technology",
  "B.Sc. Optometry",
  "B.Sc. Nursing",
  "B.Sc. Cardiac Technology",
  "B.Sc. Respiratory Therapy",
  "B.Sc. Dialysis Technology",
  "B.Sc. Emergency Medical Care",
  "B.Sc. Yoga",
  "B.Sc. Physical Education",
  "B.Sc. Sports Science",
  "B.Com.",
  "B.Com. Computer Applications",
  "B.Com. Accounting and Finance",
  "B.Com. Professional Accounting",
  "B.Com. Banking and Insurance",
  "B.Com. Corporate Secretaryship",
  "B.Com. Business Process Services",
  "B.Com. Taxation",
  "B.Com. Finance",
  "B.Com. Financial Markets",
  "B.Com. International Business",
  "B.Com. E-Commerce",
  "B.Com. Honors",
  "B.B.A.",
  "B.B.A. Computer Applications",
  "B.B.A. Business Analytics",
  "B.B.A. Logistics",
  "B.B.A. Aviation Management",
  "B.B.A. Hospital Management",
  "B.B.A. Retail Management",
  "B.B.A. Human Resource Management",
  "B.B.A. International Business",
  "B.B.A. Entrepreneurship",
  "B.B.A. Finance",
  "B.B.A. Marketing",
  "B.C.A.",
  "B.C.A. Artificial Intelligence",
  "B.C.A. Data Science",
  "B.C.A. Cyber Security",
  "B.C.A. Cloud Computing",
  "B.C.A. Internet of Things",
  "B.S.W.",
  "B.Lib.I.Sc.",
  "B.Voc. Software Development",
  "B.Voc. Banking and Financial Services",
  "B.Voc. Retail Management",
  "B.Voc. Healthcare",
  "B.Voc. Tourism and Hospitality",
  "B.Voc. Animation",
  "B.Voc. Multimedia",
  "B.Voc. Fashion Technology",
  "M.A. English",
  "M.A. Tamil",
  "M.A. History",
  "M.A. Economics",
  "M.A. Sociology",
  "M.A. Political Science",
  "M.A. Public Administration",
  "M.A. Journalism and Mass Communication",
  "M.A. Psychology",
  "M.A. Philosophy",
  "M.Sc. Computer Science",
  "M.Sc. Information Technology",
  "M.Sc. Artificial Intelligence",
  "M.Sc. Artificial Intelligence and Machine Learning",
  "M.Sc. Data Science",
  "M.Sc. Cyber Security",
  "M.Sc. Mathematics",
  "M.Sc. Statistics",
  "M.Sc. Physics",
  "M.Sc. Chemistry",
  "M.Sc. Biotechnology",
  "M.Sc. Biochemistry",
  "M.Sc. Microbiology",
  "M.Sc. Botany",
  "M.Sc. Zoology",
  "M.Sc. Psychology",
  "M.Sc. Forensic Science",
  "M.Sc. Environmental Science",
  "M.Sc. Electronics",
  "M.Sc. Food Science and Nutrition",
  "M.Sc. Software Systems",
  "M.Com.",
  "M.Com. Computer Applications",
  "M.Com. Finance",
  "M.Com. Banking",
  "M.Com. International Business",
  "M.B.A.",
  "M.B.A. Finance",
  "M.B.A. Marketing",
  "M.B.A. Human Resource Management",
  "M.B.A. Business Analytics",
  "M.B.A. Logistics and Supply Chain Management",
  "M.B.A. Hospital Management",
  "M.B.A. International Business",
  "M.B.A. Operations Management",
  "M.B.A. Systems Management",
  "M.C.A.",
  "M.C.A. Artificial Intelligence",
  "M.C.A. Data Science",
  "M.C.A. Cloud Computing",
  "M.C.A. Cyber Security",
  "M.S.W.",
  "M.Lib.I.Sc.",
  "M.Phil.",
  "Ph.D.",
] as const;

export type CollegeType = "engineering" | "arts_and_science" | "unspecified";

const ENGINEERING_NAME_PATTERN = /\bengineering\b|\binstitute of technology\b|\bpolytechnic\b/i;
const ARTS_SCIENCE_NAME_PATTERN = /\barts\b.*\bscience\b|\bscience\b.*\barts\b|\bcommerce\b|\barts\b|\bscience\b/i;

// Name-based inference only — the institution record has no explicit college-
// type field. Engineering is checked first since an engineering college's
// name never also matches the arts/science pattern below.
export function inferCollegeType(collegeName?: string | null): CollegeType {
  if (!collegeName) return "unspecified";
  if (ENGINEERING_NAME_PATTERN.test(collegeName)) return "engineering";
  if (ARTS_SCIENCE_NAME_PATTERN.test(collegeName)) return "arts_and_science";
  return "unspecified";
}

// Departments selectable for a given college name. Unspecified/ambiguous
// names get the union of both catalogs rather than an empty or guessed list.
export function getDepartmentOptions(collegeName?: string | null): string[] {
  const type = inferCollegeType(collegeName);
  if (type === "engineering") return [...ENGINEERING_DEPARTMENTS];
  if (type === "arts_and_science") return [...ARTS_SCIENCE_DEPARTMENTS];
  return [...ENGINEERING_DEPARTMENTS, ...ARTS_SCIENCE_DEPARTMENTS];
}
